/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.search-results[_ngcontent-%COMP%]   width[_ngcontent-%COMP%]:   100%[_ngcontent-%COMP%]   height[_ngcontent-%COMP%]:   400px[_ngcontent-%COMP%]   overflow-y[_ngcontent-%COMP%]:   auto[_ngcontent-%COMP%]   z-index[_ngcontent-%COMP%]:   1[_ngcontent-%COMP%]   top[_ngcontent-%COMP%]:   60px[_ngcontent-%COMP%]   position[_ngcontent-%COMP%]:   absolute[_ngcontent-%COMP%]   background-color[_ngcontent-%COMP%]:   #ffffff[_ngcontent-%COMP%]   box-shadow[_ngcontent-%COMP%]:   5px[_ngcontent-%COMP%]   5px[_ngcontent-%COMP%]   10px[_ngcontent-%COMP%]   0px[_ngcontent-%COMP%]   rgba(212[_ngcontent-%COMP%], 212[_ngcontent-%COMP%], 212[_ngcontent-%COMP%], 1)[_ngcontent-%COMP%];\r\n\r\n.spinner\r\n  display: block\r\n  margin-left: auto\r\n  margin-right: auto'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovd29ya2JlbmNoL3RyYWluaW5ncy9hbmd1bGFyL25nLXB3YS9zcmMvYXBwL2Jvb2svYm9vay10b3AtbmF2aWdhdGlvbi9ib29rLXRvcC1uYXZpZ2F0aW9uLmNvbXBvbmVudC5zYXNzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L3dvcmtiZW5jaC90cmFpbmluZ3MvYW5ndWxhci9uZy1wd2Evc3JjL2FwcC9ib29rL2Jvb2stdG9wLW5hdmlnYXRpb24vYm9vay10b3AtbmF2aWdhdGlvbi5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
