/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['\\-shadowcsshost-no-combinator   display[_ngcontent-%COMP%]:   flex[_ngcontent-%COMP%]   flex-direction[_ngcontent-%COMP%]:   row[_ngcontent-%COMP%]   flex-flow[_ngcontent-%COMP%]:   row[_ngcontent-%COMP%]   wrap[_ngcontent-%COMP%]   margin[_ngcontent-%COMP%]:   16px[_ngcontent-%COMP%]   margin-left[_ngcontent-%COMP%]:   0[_ngcontent-%COMP%]   &[_ngcontent-%COMP%]:hover   box-shadow[_ngcontent-%COMP%]:   5px[_ngcontent-%COMP%]   5px[_ngcontent-%COMP%]   10px[_ngcontent-%COMP%]   0px[_ngcontent-%COMP%]   rgba(212[_ngcontent-%COMP%], 212[_ngcontent-%COMP%], 212[_ngcontent-%COMP%], 1)[_ngcontent-%COMP%];\r\n\r\n  a\r\n    display: flex\r\n    flex-direction: row\r\n    text-decoration: none\r\n    color: #565656\r\n\r\n    .content\r\n      display: flex\r\n      flex-direction: column\r\n      margin-left: 8px'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovd29ya2JlbmNoL3RyYWluaW5ncy9hbmd1bGFyL25nLXB3YS9zcmMvYXBwL2Jvb2svYm9vay1saXN0LWVsZW1lbnQvYm9vay1saXN0LWVsZW1lbnQuY29tcG9uZW50LnNhc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovd29ya2JlbmNoL3RyYWluaW5ncy9hbmd1bGFyL25nLXB3YS9zcmMvYXBwL2Jvb2svYm9vay1saXN0LWVsZW1lbnQvYm9vay1saXN0LWVsZW1lbnQuY29tcG9uZW50LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
