/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from './not-found.component.sass.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '../../../../../src/app/not-found/not-found.component';
const styles_NotFoundComponent:any[] = [import0.styles];
export const RenderType_NotFoundComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_NotFoundComponent,
  data: {}
}
);
export function View_NotFoundComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n  not-found works!\n'])),
    (l()(),import1.ɵted((null as any),['\n']))
  ]
  ,(null as any),(null as any));
}
function View_NotFoundComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'tr-not-found',([] as any[]),(null as any),(null as any),(null as any),View_NotFoundComponent_0,RenderType_NotFoundComponent)),
    import1.ɵdid(114688,(null as any),0,import2.NotFoundComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const NotFoundComponentNgFactory:import1.ComponentFactory<import2.NotFoundComponent> = import1.ɵccf('tr-not-found',import2.NotFoundComponent,View_NotFoundComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovd29ya2JlbmNoL3RyYWluaW5ncy9hbmd1bGFyL25nLXB3YS9zcmMvYXBwL25vdC1mb3VuZC9ub3QtZm91bmQuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L3dvcmtiZW5jaC90cmFpbmluZ3MvYW5ndWxhci9uZy1wd2Evc3JjL2FwcC9ub3QtZm91bmQvbm90LWZvdW5kLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L3dvcmtiZW5jaC90cmFpbmluZ3MvYW5ndWxhci9uZy1wd2Evc3JjL2FwcC9ub3QtZm91bmQvbm90LWZvdW5kLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovd29ya2JlbmNoL3RyYWluaW5ncy9hbmd1bGFyL25nLXB3YS9zcmMvYXBwL25vdC1mb3VuZC9ub3QtZm91bmQuY29tcG9uZW50LnRzLk5vdEZvdW5kQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPHA+XG4gIG5vdC1mb3VuZCB3b3JrcyFcbjwvcD5cbiIsIjx0ci1ub3QtZm91bmQ+PC90ci1ub3QtZm91bmQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtJQUFHO0lBRUM7Ozs7OztJQ0ZKO2dCQUFBOzs7SUFBQTs7OyJ9
