/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../../src/app/loading/loading.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/router';
import * as import4 from '../../../../../src/app/loading/loading-routing.module';
import * as import5 from './app-loading-indicator/app-loading-indicator.component.ngfactory';
import * as import6 from '../../../../../src/app/loading/app-loading-indicator/app-loading-indicator.component';
class LoadingModuleInjector extends import0.ɵNgModuleInjector<import1.LoadingModule> {
  _CommonModule_0:import2.CommonModule;
  _RouterModule_1:import3.RouterModule;
  _LoadingRoutingModule_2:import4.LoadingRoutingModule;
  _LoadingModule_3:import1.LoadingModule;
  __NgLocalization_4:import2.NgLocaleLocalization;
  _ROUTES_5:any[];
  constructor(parent:import0.Injector) {
    super(parent,[import5.AppLoadingIndicatorComponentNgFactory],([] as any[]));
  }
  get _NgLocalization_4():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_4 == null)) { (this.__NgLocalization_4 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_4;
  }
  createInternal():import1.LoadingModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._RouterModule_1 = new import3.RouterModule(this.parent.get(import3.ɵa,(null as any)),this.parent.get(import3.Router,(null as any)));
    this._LoadingRoutingModule_2 = new import4.LoadingRoutingModule();
    this._LoadingModule_3 = new import1.LoadingModule();
        this._ROUTES_5 = [[{
          path: 'loading',
          component: import6.AppLoadingIndicatorComponent
        }
    ]];
    return this._LoadingModule_3;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.RouterModule)) { return this._RouterModule_1; }
    if ((token === import4.LoadingRoutingModule)) { return this._LoadingRoutingModule_2; }
    if ((token === import1.LoadingModule)) { return this._LoadingModule_3; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_4; }
    if ((token === import3.ROUTES)) { return this._ROUTES_5; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const LoadingModuleNgFactory:import0.NgModuleFactory<import1.LoadingModule> = new import0.NgModuleFactory<any>(LoadingModuleInjector,import1.LoadingModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovd29ya2JlbmNoL3RyYWluaW5ncy9hbmd1bGFyL25nLXB3YS9zcmMvYXBwL2xvYWRpbmcvbG9hZGluZy5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovd29ya2JlbmNoL3RyYWluaW5ncy9hbmd1bGFyL25nLXB3YS9zcmMvYXBwL2xvYWRpbmcvbG9hZGluZy5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
