/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../../src/app/loading/loading-routing.module';
import * as import2 from '@angular/router';
import * as import3 from './app-loading-indicator/app-loading-indicator.component.ngfactory';
import * as import4 from '../../../../../src/app/loading/app-loading-indicator/app-loading-indicator.component';
class LoadingRoutingModuleInjector extends import0.ɵNgModuleInjector<import1.LoadingRoutingModule> {
  _RouterModule_0:import2.RouterModule;
  _LoadingRoutingModule_1:import1.LoadingRoutingModule;
  _ROUTES_2:any[];
  constructor(parent:import0.Injector) {
    super(parent,[import3.AppLoadingIndicatorComponentNgFactory],([] as any[]));
  }
  createInternal():import1.LoadingRoutingModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ɵa,(null as any)),this.parent.get(import2.Router,(null as any)));
    this._LoadingRoutingModule_1 = new import1.LoadingRoutingModule();
        this._ROUTES_2 = [[{
          path: 'loading',
          component: import4.AppLoadingIndicatorComponent
        }
    ]];
    return this._LoadingRoutingModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import1.LoadingRoutingModule)) { return this._LoadingRoutingModule_1; }
    if ((token === import2.ROUTES)) { return this._ROUTES_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const LoadingRoutingModuleNgFactory:import0.NgModuleFactory<import1.LoadingRoutingModule> = new import0.NgModuleFactory<any>(LoadingRoutingModuleInjector,import1.LoadingRoutingModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovd29ya2JlbmNoL3RyYWluaW5ncy9hbmd1bGFyL25nLXB3YS9zcmMvYXBwL2xvYWRpbmcvbG9hZGluZy1yb3V0aW5nLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi93b3JrYmVuY2gvdHJhaW5pbmdzL2FuZ3VsYXIvbmctcHdhL3NyYy9hcHAvbG9hZGluZy9sb2FkaW5nLXJvdXRpbmcubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
