/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from './rating-button.component.sass.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '../../../../../../src/app/book/rating-button/rating-button.component';
import * as import3 from '../../../../../../src/app/utilities/event-modifiers/click-once.directive';
const styles_RatingButtonComponent:any[] = [import0.styles];
export const RenderType_RatingButtonComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_RatingButtonComponent,
  data: {}
}
);
export function View_RatingButtonComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
      (l()(),import1.ɵeld(0,(null as any),(null as any),9,'div',[[
        'class',
        'btn-group btn-sm'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n  '])),
      (l()(),import1.ɵeld(0,(null as any),(null as any),2,'button',[[
        'class',
        'btn'
      ]
      ],(null as any),[[
        (null as any),
        'click.once'
      ]
    ],(v,en,$event) => {
      var ad:boolean = true;
      var co:import2.RatingButtonComponent = v.component;
      if (('click.once' === en)) {
        const pd_0:any = ((<any>co.raiseIncrease()) !== false);
        ad = (pd_0 && ad);
      }
      return ad;
    },(null as any),(null as any))),
    import1.ɵdid(81920,(null as any),0,import3.ClickOnceDirective,[
      import1.Renderer2,
      import1.ElementRef
    ]
    ,(null as any),{clickOnce: 'click.once'}),
    (l()(),import1.ɵted((null as any),['+'])),
    (l()(),import1.ɵted((null as any),['\n  '])),
      (l()(),import1.ɵeld(0,(null as any),(null as any),2,'button',[[
        'class',
        'btn'
      ]
      ],(null as any),[[
        (null as any),
        'click.once'
      ]
    ],(v,en,$event) => {
      var ad:boolean = true;
      var co:import2.RatingButtonComponent = v.component;
      if (('click.once' === en)) {
        const pd_0:any = ((<any>co.raiseDecrease()) !== false);
        ad = (pd_0 && ad);
      }
      return ad;
    },(null as any),(null as any))),
    import1.ɵdid(81920,(null as any),0,import3.ClickOnceDirective,[
      import1.Renderer2,
      import1.ElementRef
    ]
    ,(null as any),{clickOnce: 'click.once'}),
    (l()(),import1.ɵted((null as any),['-'])),
    (l()(),import1.ɵted((null as any),['\n'])),
    (l()(),import1.ɵted((null as any),['\n']))
  ]
  ,(ck,v) => {
    ck(v,3,0);
    ck(v,7,0);
  },(null as any));
}
function View_RatingButtonComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'tr-rating-button',([] as any[]),(null as any),(null as any),(null as any),View_RatingButtonComponent_0,RenderType_RatingButtonComponent)),
    import1.ɵdid(49152,(null as any),0,import2.RatingButtonComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const RatingButtonComponentNgFactory:import1.ComponentFactory<import2.RatingButtonComponent> = import1.ɵccf('tr-rating-button',import2.RatingButtonComponent,View_RatingButtonComponent_Host_0,{rating: 'rating'},{
  increase: 'increase',
  decrease: 'decrease'
}
,([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovd29ya2JlbmNoL3RyYWluaW5ncy9hbmd1bGFyL25nLXB3YS9zcmMvYXBwL2Jvb2svcmF0aW5nLWJ1dHRvbi9yYXRpbmctYnV0dG9uLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi93b3JrYmVuY2gvdHJhaW5pbmdzL2FuZ3VsYXIvbmctcHdhL3NyYy9hcHAvYm9vay9yYXRpbmctYnV0dG9uL3JhdGluZy1idXR0b24uY29tcG9uZW50LnRzIiwibmc6Ly8vQzovd29ya2JlbmNoL3RyYWluaW5ncy9hbmd1bGFyL25nLXB3YS9zcmMvYXBwL2Jvb2svcmF0aW5nLWJ1dHRvbi9yYXRpbmctYnV0dG9uLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovd29ya2JlbmNoL3RyYWluaW5ncy9hbmd1bGFyL25nLXB3YS9zcmMvYXBwL2Jvb2svcmF0aW5nLWJ1dHRvbi9yYXRpbmctYnV0dG9uLmNvbXBvbmVudC50cy5SYXRpbmdCdXR0b25Db21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2IGNsYXNzPVwiYnRuLWdyb3VwIGJ0bi1zbVwiPlxuICA8YnV0dG9uIGNsYXNzPVwiYnRuXCIgKGNsaWNrLm9uY2UpPVwicmFpc2VJbmNyZWFzZSgpXCI+KzwvYnV0dG9uPlxuICA8YnV0dG9uIGNsYXNzPVwiYnRuXCIgKGNsaWNrLm9uY2UpPVwicmFpc2VEZWNyZWFzZSgpXCI+LTwvYnV0dG9uPlxuPC9kaXY+XG4iLCI8dHItcmF0aW5nLWJ1dHRvbj48L3RyLXJhdGluZy1idXR0b24+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O01DQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUE4QjtNQUM1QjtRQUFBO1FBQUE7TUFBQTtNQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7TUFBQTtNQUFBO01BQW9CO1FBQUE7UUFBQTtNQUFBO01BQXBCO0lBQUE7Z0JBQUE7OztJQUFBO0tBQUE7SUFBbUQ7SUFBVTtNQUM3RDtRQUFBO1FBQUE7TUFBQTtNQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7TUFBQTtNQUFBO01BQW9CO1FBQUE7UUFBQTtNQUFBO01BQXBCO0lBQUE7Z0JBQUE7OztJQUFBO0tBQUE7SUFBbUQ7SUFBVTtJQUN6RDs7O0lBRko7SUFDQTs7Ozs7SUNGRjtnQkFBQTs7Ozs7Ozs7In0=
