/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../../src/app/book/book.routing.module';
import * as import2 from '@angular/router';
import * as import3 from '../../../../../src/app/book/core/guards/book-edit.guard';
import * as import4 from './book-dashboard/book-dashboard.component.ngfactory';
import * as import5 from './book-details/book-details.component.ngfactory';
import * as import6 from './book-edit/book-edit.component.ngfactory';
import * as import7 from '../../../../../src/app/book/book-dashboard/book-dashboard.component';
import * as import8 from '../../../../../src/app/book/book-details/book-details.component';
import * as import9 from '../../../../../src/app/book/core/resolvers/book.resolver';
import * as import10 from '../../../../../src/app/book/book-edit/book-edit.component';
class BookRoutingModuleInjector extends import0.ɵNgModuleInjector<import1.BookRoutingModule> {
  _RouterModule_0:import2.RouterModule;
  _BookRoutingModule_1:import1.BookRoutingModule;
  _ROUTES_2:any[];
  __BookEditGuard_3:import3.BookEditGuard;
  constructor(parent:import0.Injector) {
    super(parent,[
      import4.BookDashboardComponentNgFactory,
      import5.BookDetailsComponentNgFactory,
      import6.BookEditComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _BookEditGuard_3():import3.BookEditGuard {
    if ((this.__BookEditGuard_3 == null)) { (this.__BookEditGuard_3 = new import3.BookEditGuard()); }
    return this.__BookEditGuard_3;
  }
  createInternal():import1.BookRoutingModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ɵa,(null as any)),this.parent.get(import2.Router,(null as any)));
    this._BookRoutingModule_1 = new import1.BookRoutingModule();
      this._ROUTES_2 = [[
        {
          path: '',
          component: import7.BookDashboardComponent,
          pathMatch: 'full'
        }
        ,
        {
          path: 'book/:isbn',
          component: import8.BookDetailsComponent,
          resolve: {book: import9.BookResolver}
        }
        ,
        {
          path: 'book/:isbn/edit',
          component: import10.BookEditComponent,
          resolve: {book: import9.BookResolver},
          canActivate: [import3.BookEditGuard]
        }

      ]
    ];
    return this._BookRoutingModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import1.BookRoutingModule)) { return this._BookRoutingModule_1; }
    if ((token === import2.ROUTES)) { return this._ROUTES_2; }
    if ((token === import3.BookEditGuard)) { return this._BookEditGuard_3; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const BookRoutingModuleNgFactory:import0.NgModuleFactory<import1.BookRoutingModule> = new import0.NgModuleFactory<any>(BookRoutingModuleInjector,import1.BookRoutingModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovd29ya2JlbmNoL3RyYWluaW5ncy9hbmd1bGFyL25nLXB3YS9zcmMvYXBwL2Jvb2svYm9vay5yb3V0aW5nLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi93b3JrYmVuY2gvdHJhaW5pbmdzL2FuZ3VsYXIvbmctcHdhL3NyYy9hcHAvYm9vay9ib29rLnJvdXRpbmcubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
