/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../../src/app/book/book.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/forms';
import * as import4 from '@angular/http';
import * as import5 from '@angular/router';
import * as import6 from '../../../../../src/app/book/book.routing.module';
import * as import7 from '../../../../../src/app/utilities/utilities.module';
import * as import8 from '../../../../../src/app/book/core/guards/book-edit.guard';
import * as import9 from '../../../../../src/app/book/core/book.bus';
import * as import10 from '../../../../../src/app/book/core/book.service';
import * as import11 from '../../../../../src/app/book/core/google-books.service';
import * as import12 from '../../../../../src/app/book/core/resolvers/book.resolver';
import * as import13 from './book-dashboard/book-dashboard.component.ngfactory';
import * as import14 from './book-details/book-details.component.ngfactory';
import * as import15 from './book-edit/book-edit.component.ngfactory';
import * as import16 from '../../../../../src/app/book/book-dashboard/book-dashboard.component';
import * as import17 from '../../../../../src/app/book/book-details/book-details.component';
import * as import18 from '../../../../../src/app/book/book-edit/book-edit.component';
class BookModuleInjector extends import0.ɵNgModuleInjector<import1.BookModule> {
  _CommonModule_0:import2.CommonModule;
  _ɵba_1:import3.ɵba;
  _FormsModule_2:import3.FormsModule;
  _ReactiveFormsModule_3:import3.ReactiveFormsModule;
  _HttpModule_4:import4.HttpModule;
  _RouterModule_5:import5.RouterModule;
  _BookRoutingModule_6:import6.BookRoutingModule;
  _UtilitiesModule_7:import7.UtilitiesModule;
  _BookModule_8:import1.BookModule;
  __NgLocalization_9:import2.NgLocaleLocalization;
  __ɵi_10:import3.ɵi;
  __FormBuilder_11:import3.FormBuilder;
  __BrowserXhr_12:import4.BrowserXhr;
  __ResponseOptions_13:import4.BaseResponseOptions;
  __XSRFStrategy_14:any;
  __XHRBackend_15:import4.XHRBackend;
  __RequestOptions_16:import4.BaseRequestOptions;
  __Http_17:any;
  _ROUTES_18:any[];
  __BookEditGuard_19:import8.BookEditGuard;
  __BookBus_20:import9.BookBus;
  __BookService_21:import10.BookService;
  __GoogleBooksService_22:import11.GoogleBooksService;
  __BookResolver_23:import12.BookResolver;
  constructor(parent:import0.Injector) {
    super(parent,[
      import13.BookDashboardComponentNgFactory,
      import14.BookDetailsComponentNgFactory,
      import15.BookEditComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _NgLocalization_9():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_9 == null)) { (this.__NgLocalization_9 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_9;
  }
  get _ɵi_10():import3.ɵi {
    if ((this.__ɵi_10 == null)) { (this.__ɵi_10 = new import3.ɵi()); }
    return this.__ɵi_10;
  }
  get _FormBuilder_11():import3.FormBuilder {
    if ((this.__FormBuilder_11 == null)) { (this.__FormBuilder_11 = new import3.FormBuilder()); }
    return this.__FormBuilder_11;
  }
  get _BrowserXhr_12():import4.BrowserXhr {
    if ((this.__BrowserXhr_12 == null)) { (this.__BrowserXhr_12 = new import4.BrowserXhr()); }
    return this.__BrowserXhr_12;
  }
  get _ResponseOptions_13():import4.BaseResponseOptions {
    if ((this.__ResponseOptions_13 == null)) { (this.__ResponseOptions_13 = new import4.BaseResponseOptions()); }
    return this.__ResponseOptions_13;
  }
  get _XSRFStrategy_14():any {
    if ((this.__XSRFStrategy_14 == null)) { (this.__XSRFStrategy_14 = import4.ɵb()); }
    return this.__XSRFStrategy_14;
  }
  get _XHRBackend_15():import4.XHRBackend {
    if ((this.__XHRBackend_15 == null)) { (this.__XHRBackend_15 = new import4.XHRBackend(this._BrowserXhr_12,this._ResponseOptions_13,this._XSRFStrategy_14)); }
    return this.__XHRBackend_15;
  }
  get _RequestOptions_16():import4.BaseRequestOptions {
    if ((this.__RequestOptions_16 == null)) { (this.__RequestOptions_16 = new import4.BaseRequestOptions()); }
    return this.__RequestOptions_16;
  }
  get _Http_17():any {
    if ((this.__Http_17 == null)) { (this.__Http_17 = import4.ɵc(this._XHRBackend_15,this._RequestOptions_16)); }
    return this.__Http_17;
  }
  get _BookEditGuard_19():import8.BookEditGuard {
    if ((this.__BookEditGuard_19 == null)) { (this.__BookEditGuard_19 = new import8.BookEditGuard()); }
    return this.__BookEditGuard_19;
  }
  get _BookBus_20():import9.BookBus {
    if ((this.__BookBus_20 == null)) { (this.__BookBus_20 = new import9.BookBus()); }
    return this.__BookBus_20;
  }
  get _BookService_21():import10.BookService {
    if ((this.__BookService_21 == null)) { (this.__BookService_21 = new import10.BookService()); }
    return this.__BookService_21;
  }
  get _GoogleBooksService_22():import11.GoogleBooksService {
    if ((this.__GoogleBooksService_22 == null)) { (this.__GoogleBooksService_22 = new import11.GoogleBooksService(this._Http_17)); }
    return this.__GoogleBooksService_22;
  }
  get _BookResolver_23():import12.BookResolver {
    if ((this.__BookResolver_23 == null)) { (this.__BookResolver_23 = new import12.BookResolver(this._BookService_21)); }
    return this.__BookResolver_23;
  }
  createInternal():import1.BookModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ɵba_1 = new import3.ɵba();
    this._FormsModule_2 = new import3.FormsModule();
    this._ReactiveFormsModule_3 = new import3.ReactiveFormsModule();
    this._HttpModule_4 = new import4.HttpModule();
    this._RouterModule_5 = new import5.RouterModule(this.parent.get(import5.ɵa,(null as any)),this.parent.get(import5.Router,(null as any)));
    this._BookRoutingModule_6 = new import6.BookRoutingModule();
    this._UtilitiesModule_7 = new import7.UtilitiesModule();
    this._BookModule_8 = new import1.BookModule();
      this._ROUTES_18 = [[
        {
          path: '',
          component: import16.BookDashboardComponent,
          pathMatch: 'full'
        }
        ,
        {
          path: 'book/:isbn',
          component: import17.BookDetailsComponent,
          resolve: {book: import12.BookResolver}
        }
        ,
        {
          path: 'book/:isbn/edit',
          component: import18.BookEditComponent,
          resolve: {book: import12.BookResolver},
          canActivate: [import8.BookEditGuard]
        }

      ]
    ];
    return this._BookModule_8;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ɵba)) { return this._ɵba_1; }
    if ((token === import3.FormsModule)) { return this._FormsModule_2; }
    if ((token === import3.ReactiveFormsModule)) { return this._ReactiveFormsModule_3; }
    if ((token === import4.HttpModule)) { return this._HttpModule_4; }
    if ((token === import5.RouterModule)) { return this._RouterModule_5; }
    if ((token === import6.BookRoutingModule)) { return this._BookRoutingModule_6; }
    if ((token === import7.UtilitiesModule)) { return this._UtilitiesModule_7; }
    if ((token === import1.BookModule)) { return this._BookModule_8; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_9; }
    if ((token === import3.ɵi)) { return this._ɵi_10; }
    if ((token === import3.FormBuilder)) { return this._FormBuilder_11; }
    if ((token === import4.BrowserXhr)) { return this._BrowserXhr_12; }
    if ((token === import4.ResponseOptions)) { return this._ResponseOptions_13; }
    if ((token === import4.XSRFStrategy)) { return this._XSRFStrategy_14; }
    if ((token === import4.XHRBackend)) { return this._XHRBackend_15; }
    if ((token === import4.RequestOptions)) { return this._RequestOptions_16; }
    if ((token === import4.Http)) { return this._Http_17; }
    if ((token === import5.ROUTES)) { return this._ROUTES_18; }
    if ((token === import8.BookEditGuard)) { return this._BookEditGuard_19; }
    if ((token === import9.BookBus)) { return this._BookBus_20; }
    if ((token === import10.BookService)) { return this._BookService_21; }
    if ((token === import11.GoogleBooksService)) { return this._GoogleBooksService_22; }
    if ((token === import12.BookResolver)) { return this._BookResolver_23; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const BookModuleNgFactory:import0.NgModuleFactory<import1.BookModule> = new import0.NgModuleFactory<any>(BookModuleInjector,import1.BookModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovd29ya2JlbmNoL3RyYWluaW5ncy9hbmd1bGFyL25nLXB3YS9zcmMvYXBwL2Jvb2svYm9vay5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovd29ya2JlbmNoL3RyYWluaW5ncy9hbmd1bGFyL25nLXB3YS9zcmMvYXBwL2Jvb2svYm9vay5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
