/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../src/app/app.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/router';
import * as import4 from '@angular/platform-browser';
import * as import5 from '@angular/forms';
import * as import6 from '@angular/http';
import * as import7 from '../../../../src/app/book/book.routing.module';
import * as import8 from '../../../../src/app/utilities/utilities.module';
import * as import9 from '../../../../src/app/book/book.module';
import * as import10 from '../../../../src/app/loading/loading-routing.module';
import * as import11 from '../../../../src/app/loading/loading.module';
import * as import12 from '../../../../src/app/app.routing.module';
import * as import13 from '../../../../src/app/book/core/guards/book-edit.guard';
import * as import14 from '../../../../src/app/book/core/book.bus';
import * as import15 from '../../../../src/app/book/core/book.service';
import * as import16 from '../../../../src/app/book/core/google-books.service';
import * as import17 from '../../../../src/app/book/core/resolvers/book.resolver';
import * as import18 from './book/book-dashboard/book-dashboard.component.ngfactory';
import * as import19 from './book/book-details/book-details.component.ngfactory';
import * as import20 from './book/book-edit/book-edit.component.ngfactory';
import * as import21 from './loading/app-loading-indicator/app-loading-indicator.component.ngfactory';
import * as import22 from './not-found/not-found.component.ngfactory';
import * as import23 from './app.component.ngfactory';
import * as import24 from '../../../../src/app/book/book-dashboard/book-dashboard.component';
import * as import25 from '../../../../src/app/book/book-details/book-details.component';
import * as import26 from '../../../../src/app/book/book-edit/book-edit.component';
import * as import27 from '../../../../src/app/loading/app-loading-indicator/app-loading-indicator.component';
import * as import28 from '../../../../src/app/not-found/not-found.component';
class AppModuleInjector extends import0.ɵNgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ErrorHandler_1:any;
  _NgProbeToken_2:any[];
  _ɵg_3:import3.ɵg;
  _APP_ID_4:any;
  _ɵTRANSITION_ID_5:any;
  _APP_INITIALIZER_6:any[];
  _ApplicationInitStatus_7:import0.ApplicationInitStatus;
  _ɵf_8:import0.ɵf;
  _ApplicationRef_9:any;
  _ApplicationModule_10:import0.ApplicationModule;
  _BrowserModule_11:import4.BrowserModule;
  _ɵba_12:import5.ɵba;
  _FormsModule_13:import5.FormsModule;
  _ReactiveFormsModule_14:import5.ReactiveFormsModule;
  _HttpModule_15:import6.HttpModule;
  _ɵa_16:any;
  _UrlSerializer_17:import3.DefaultUrlSerializer;
  _RouterOutletMap_18:import3.RouterOutletMap;
  _ROUTER_CONFIGURATION_19:any;
  _LocationStrategy_20:any;
  _Location_21:import2.Location;
  _Compiler_22:import0.Compiler;
  _NgModuleFactoryLoader_23:import0.SystemJsNgModuleLoader;
  _ROUTES_24:any[];
  _Router_25:any;
  _RouterModule_26:import3.RouterModule;
  _BookRoutingModule_27:import7.BookRoutingModule;
  _UtilitiesModule_28:import8.UtilitiesModule;
  _BookModule_29:import9.BookModule;
  _LoadingRoutingModule_30:import10.LoadingRoutingModule;
  _LoadingModule_31:import11.LoadingModule;
  _AppRoutingModule_32:import12.AppRoutingModule;
  _AppModule_33:import1.AppModule;
  __LOCALE_ID_34:any;
  __NgLocalization_35:import2.NgLocaleLocalization;
  __IterableDiffers_36:any;
  __KeyValueDiffers_37:any;
  __DomSanitizer_38:import4.ɵe;
  __Sanitizer_39:any;
  __HAMMER_GESTURE_CONFIG_40:import4.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_41:any[];
  __EventManager_42:import4.EventManager;
  __ɵDomSharedStylesHost_43:import4.ɵDomSharedStylesHost;
  __ɵDomRendererFactory2_44:import4.ɵDomRendererFactory2;
  __RendererFactory2_45:any;
  __ɵSharedStylesHost_46:any;
  __Testability_47:import0.Testability;
  __Meta_48:import4.Meta;
  __Title_49:import4.Title;
  __ɵi_50:import5.ɵi;
  __FormBuilder_51:import5.FormBuilder;
  __BrowserXhr_52:import6.BrowserXhr;
  __ResponseOptions_53:import6.BaseResponseOptions;
  __XSRFStrategy_54:any;
  __XHRBackend_55:import6.XHRBackend;
  __RequestOptions_56:import6.BaseRequestOptions;
  __Http_57:any;
  __BookEditGuard_58:import13.BookEditGuard;
  __BookBus_59:import14.BookBus;
  __BookService_60:import15.BookService;
  __GoogleBooksService_61:import16.GoogleBooksService;
  __BookResolver_62:import17.BookResolver;
  __ActivatedRoute_63:any;
  __NoPreloading_64:import3.NoPreloading;
  __PreloadingStrategy_65:any;
  __RouterPreloader_66:import3.RouterPreloader;
  __PreloadAllModules_67:import3.PreloadAllModules;
  __ROUTER_INITIALIZER_68:any;
  __APP_BOOTSTRAP_LISTENER_69:any[];
  constructor(parent:import0.Injector) {
    super(parent,[
      import18.BookDashboardComponentNgFactory,
      import19.BookDetailsComponentNgFactory,
      import20.BookEditComponentNgFactory,
      import21.AppLoadingIndicatorComponentNgFactory,
      import22.NotFoundComponentNgFactory,
      import23.AppComponentNgFactory
    ]
    ,[import23.AppComponentNgFactory]);
  }
  get _LOCALE_ID_34():any {
    if ((this.__LOCALE_ID_34 == null)) { (this.__LOCALE_ID_34 = import0.ɵn(this.parent.get(import0.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_34;
  }
  get _NgLocalization_35():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_35 == null)) { (this.__NgLocalization_35 = new import2.NgLocaleLocalization(this._LOCALE_ID_34)); }
    return this.__NgLocalization_35;
  }
  get _IterableDiffers_36():any {
    if ((this.__IterableDiffers_36 == null)) { (this.__IterableDiffers_36 = import0.ɵl()); }
    return this.__IterableDiffers_36;
  }
  get _KeyValueDiffers_37():any {
    if ((this.__KeyValueDiffers_37 == null)) { (this.__KeyValueDiffers_37 = import0.ɵm()); }
    return this.__KeyValueDiffers_37;
  }
  get _DomSanitizer_38():import4.ɵe {
    if ((this.__DomSanitizer_38 == null)) { (this.__DomSanitizer_38 = new import4.ɵe(this.parent.get(import4.DOCUMENT))); }
    return this.__DomSanitizer_38;
  }
  get _Sanitizer_39():any {
    if ((this.__Sanitizer_39 == null)) { (this.__Sanitizer_39 = this._DomSanitizer_38); }
    return this.__Sanitizer_39;
  }
  get _HAMMER_GESTURE_CONFIG_40():import4.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_40 == null)) { (this.__HAMMER_GESTURE_CONFIG_40 = new import4.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_40;
  }
  get _EVENT_MANAGER_PLUGINS_41():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_41 == null)) { (this.__EVENT_MANAGER_PLUGINS_41 = [
      new import4.ɵDomEventsPlugin(this.parent.get(import4.DOCUMENT)),
      new import4.ɵKeyEventsPlugin(this.parent.get(import4.DOCUMENT)),
      new import4.ɵHammerGesturesPlugin(this.parent.get(import4.DOCUMENT),this._HAMMER_GESTURE_CONFIG_40)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_41;
  }
  get _EventManager_42():import4.EventManager {
    if ((this.__EventManager_42 == null)) { (this.__EventManager_42 = new import4.EventManager(this._EVENT_MANAGER_PLUGINS_41,this.parent.get(import0.NgZone))); }
    return this.__EventManager_42;
  }
  get _ɵDomSharedStylesHost_43():import4.ɵDomSharedStylesHost {
    if ((this.__ɵDomSharedStylesHost_43 == null)) { (this.__ɵDomSharedStylesHost_43 = new import4.ɵDomSharedStylesHost(this.parent.get(import4.DOCUMENT))); }
    return this.__ɵDomSharedStylesHost_43;
  }
  get _ɵDomRendererFactory2_44():import4.ɵDomRendererFactory2 {
    if ((this.__ɵDomRendererFactory2_44 == null)) { (this.__ɵDomRendererFactory2_44 = new import4.ɵDomRendererFactory2(this._EventManager_42,this._ɵDomSharedStylesHost_43)); }
    return this.__ɵDomRendererFactory2_44;
  }
  get _RendererFactory2_45():any {
    if ((this.__RendererFactory2_45 == null)) { (this.__RendererFactory2_45 = this._ɵDomRendererFactory2_44); }
    return this.__RendererFactory2_45;
  }
  get _ɵSharedStylesHost_46():any {
    if ((this.__ɵSharedStylesHost_46 == null)) { (this.__ɵSharedStylesHost_46 = this._ɵDomSharedStylesHost_43); }
    return this.__ɵSharedStylesHost_46;
  }
  get _Testability_47():import0.Testability {
    if ((this.__Testability_47 == null)) { (this.__Testability_47 = new import0.Testability(this.parent.get(import0.NgZone))); }
    return this.__Testability_47;
  }
  get _Meta_48():import4.Meta {
    if ((this.__Meta_48 == null)) { (this.__Meta_48 = new import4.Meta(this.parent.get(import4.DOCUMENT))); }
    return this.__Meta_48;
  }
  get _Title_49():import4.Title {
    if ((this.__Title_49 == null)) { (this.__Title_49 = new import4.Title(this.parent.get(import4.DOCUMENT))); }
    return this.__Title_49;
  }
  get _ɵi_50():import5.ɵi {
    if ((this.__ɵi_50 == null)) { (this.__ɵi_50 = new import5.ɵi()); }
    return this.__ɵi_50;
  }
  get _FormBuilder_51():import5.FormBuilder {
    if ((this.__FormBuilder_51 == null)) { (this.__FormBuilder_51 = new import5.FormBuilder()); }
    return this.__FormBuilder_51;
  }
  get _BrowserXhr_52():import6.BrowserXhr {
    if ((this.__BrowserXhr_52 == null)) { (this.__BrowserXhr_52 = new import6.BrowserXhr()); }
    return this.__BrowserXhr_52;
  }
  get _ResponseOptions_53():import6.BaseResponseOptions {
    if ((this.__ResponseOptions_53 == null)) { (this.__ResponseOptions_53 = new import6.BaseResponseOptions()); }
    return this.__ResponseOptions_53;
  }
  get _XSRFStrategy_54():any {
    if ((this.__XSRFStrategy_54 == null)) { (this.__XSRFStrategy_54 = import6.ɵb()); }
    return this.__XSRFStrategy_54;
  }
  get _XHRBackend_55():import6.XHRBackend {
    if ((this.__XHRBackend_55 == null)) { (this.__XHRBackend_55 = new import6.XHRBackend(this._BrowserXhr_52,this._ResponseOptions_53,this._XSRFStrategy_54)); }
    return this.__XHRBackend_55;
  }
  get _RequestOptions_56():import6.BaseRequestOptions {
    if ((this.__RequestOptions_56 == null)) { (this.__RequestOptions_56 = new import6.BaseRequestOptions()); }
    return this.__RequestOptions_56;
  }
  get _Http_57():any {
    if ((this.__Http_57 == null)) { (this.__Http_57 = import6.ɵc(this._XHRBackend_55,this._RequestOptions_56)); }
    return this.__Http_57;
  }
  get _BookEditGuard_58():import13.BookEditGuard {
    if ((this.__BookEditGuard_58 == null)) { (this.__BookEditGuard_58 = new import13.BookEditGuard()); }
    return this.__BookEditGuard_58;
  }
  get _BookBus_59():import14.BookBus {
    if ((this.__BookBus_59 == null)) { (this.__BookBus_59 = new import14.BookBus()); }
    return this.__BookBus_59;
  }
  get _BookService_60():import15.BookService {
    if ((this.__BookService_60 == null)) { (this.__BookService_60 = new import15.BookService()); }
    return this.__BookService_60;
  }
  get _GoogleBooksService_61():import16.GoogleBooksService {
    if ((this.__GoogleBooksService_61 == null)) { (this.__GoogleBooksService_61 = new import16.GoogleBooksService(this._Http_57)); }
    return this.__GoogleBooksService_61;
  }
  get _BookResolver_62():import17.BookResolver {
    if ((this.__BookResolver_62 == null)) { (this.__BookResolver_62 = new import17.BookResolver(this._BookService_60)); }
    return this.__BookResolver_62;
  }
  get _ActivatedRoute_63():any {
    if ((this.__ActivatedRoute_63 == null)) { (this.__ActivatedRoute_63 = import3.ɵf(this._Router_25)); }
    return this.__ActivatedRoute_63;
  }
  get _NoPreloading_64():import3.NoPreloading {
    if ((this.__NoPreloading_64 == null)) { (this.__NoPreloading_64 = new import3.NoPreloading()); }
    return this.__NoPreloading_64;
  }
  get _PreloadingStrategy_65():any {
    if ((this.__PreloadingStrategy_65 == null)) { (this.__PreloadingStrategy_65 = this._NoPreloading_64); }
    return this.__PreloadingStrategy_65;
  }
  get _RouterPreloader_66():import3.RouterPreloader {
    if ((this.__RouterPreloader_66 == null)) { (this.__RouterPreloader_66 = new import3.RouterPreloader(this._Router_25,this._NgModuleFactoryLoader_23,this._Compiler_22,this,this._PreloadingStrategy_65)); }
    return this.__RouterPreloader_66;
  }
  get _PreloadAllModules_67():import3.PreloadAllModules {
    if ((this.__PreloadAllModules_67 == null)) { (this.__PreloadAllModules_67 = new import3.PreloadAllModules()); }
    return this.__PreloadAllModules_67;
  }
  get _ROUTER_INITIALIZER_68():any {
    if ((this.__ROUTER_INITIALIZER_68 == null)) { (this.__ROUTER_INITIALIZER_68 = import3.ɵi(this._ɵg_3)); }
    return this.__ROUTER_INITIALIZER_68;
  }
  get _APP_BOOTSTRAP_LISTENER_69():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_69 == null)) { (this.__APP_BOOTSTRAP_LISTENER_69 = [this._ROUTER_INITIALIZER_68]); }
    return this.__APP_BOOTSTRAP_LISTENER_69;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ErrorHandler_1 = import4.ɵa();
    this._NgProbeToken_2 = [import3.ɵb()];
    this._ɵg_3 = new import3.ɵg(this);
    this._APP_ID_4 = 'buecher';
    this._ɵTRANSITION_ID_5 = this._APP_ID_4;
    this._APP_INITIALIZER_6 = [
      import0.ɵo,
      import4.ɵc(this.parent.get(import4.NgProbeToken,(null as any)),this._NgProbeToken_2),
      import3.ɵh(this._ɵg_3),
      import4.ɵf(this._ɵTRANSITION_ID_5,this.parent.get(import4.DOCUMENT),this)
    ]
    ;
    this._ApplicationInitStatus_7 = new import0.ApplicationInitStatus(this._APP_INITIALIZER_6);
    this._ɵf_8 = new import0.ɵf(this.parent.get(import0.NgZone),this.parent.get(import0.ɵConsole),this,this._ErrorHandler_1,this.componentFactoryResolver,this._ApplicationInitStatus_7);
    this._ApplicationRef_9 = this._ɵf_8;
    this._ApplicationModule_10 = new import0.ApplicationModule(this._ApplicationRef_9);
    this._BrowserModule_11 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._ɵba_12 = new import5.ɵba();
    this._FormsModule_13 = new import5.FormsModule();
    this._ReactiveFormsModule_14 = new import5.ReactiveFormsModule();
    this._HttpModule_15 = new import6.HttpModule();
    this._ɵa_16 = import3.ɵd(this.parent.get(import3.Router,(null as any)));
    this._UrlSerializer_17 = new import3.DefaultUrlSerializer();
    this._RouterOutletMap_18 = new import3.RouterOutletMap();
    this._ROUTER_CONFIGURATION_19 = {};
    this._LocationStrategy_20 = import3.ɵc(this.parent.get(import2.PlatformLocation),this.parent.get(import2.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_19);
    this._Location_21 = new import2.Location(this._LocationStrategy_20);
    this._Compiler_22 = new import0.Compiler();
    this._NgModuleFactoryLoader_23 = new import0.SystemJsNgModuleLoader(this._Compiler_22,this.parent.get(import0.SystemJsNgModuleLoaderConfig,(null as any)));
    this._ROUTES_24 = [
      [
        {
          path: '',
          component: import24.BookDashboardComponent,
          pathMatch: 'full'
        }
        ,
        {
          path: 'book/:isbn',
          component: import25.BookDetailsComponent,
          resolve: {book: import17.BookResolver}
        }
        ,
        {
          path: 'book/:isbn/edit',
          component: import26.BookEditComponent,
          resolve: {book: import17.BookResolver},
          canActivate: [import13.BookEditGuard]
        }

      ]
      ,
        [{
          path: 'loading',
          component: import27.AppLoadingIndicatorComponent
        }
      ],
        [{
          path: '**',
          component: import28.NotFoundComponent
        }
      ]
    ]
    ;
    this._Router_25 = import3.ɵe(this._ApplicationRef_9,this._UrlSerializer_17,this._RouterOutletMap_18,this._Location_21,this,this._NgModuleFactoryLoader_23,this._Compiler_22,this._ROUTES_24,this._ROUTER_CONFIGURATION_19,this.parent.get(import3.UrlHandlingStrategy,(null as any)),this.parent.get(import3.RouteReuseStrategy,(null as any)));
    this._RouterModule_26 = new import3.RouterModule(this._ɵa_16,this._Router_25);
    this._BookRoutingModule_27 = new import7.BookRoutingModule();
    this._UtilitiesModule_28 = new import8.UtilitiesModule();
    this._BookModule_29 = new import9.BookModule();
    this._LoadingRoutingModule_30 = new import10.LoadingRoutingModule();
    this._LoadingModule_31 = new import11.LoadingModule();
    this._AppRoutingModule_32 = new import12.AppRoutingModule();
    this._AppModule_33 = new import1.AppModule();
    return this._AppModule_33;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import0.ErrorHandler)) { return this._ErrorHandler_1; }
    if ((token === import0.NgProbeToken)) { return this._NgProbeToken_2; }
    if ((token === import3.ɵg)) { return this._ɵg_3; }
    if ((token === import0.APP_ID)) { return this._APP_ID_4; }
    if ((token === import4.ɵTRANSITION_ID)) { return this._ɵTRANSITION_ID_5; }
    if ((token === import0.APP_INITIALIZER)) { return this._APP_INITIALIZER_6; }
    if ((token === import0.ApplicationInitStatus)) { return this._ApplicationInitStatus_7; }
    if ((token === import0.ɵf)) { return this._ɵf_8; }
    if ((token === import0.ApplicationRef)) { return this._ApplicationRef_9; }
    if ((token === import0.ApplicationModule)) { return this._ApplicationModule_10; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_11; }
    if ((token === import5.ɵba)) { return this._ɵba_12; }
    if ((token === import5.FormsModule)) { return this._FormsModule_13; }
    if ((token === import5.ReactiveFormsModule)) { return this._ReactiveFormsModule_14; }
    if ((token === import6.HttpModule)) { return this._HttpModule_15; }
    if ((token === import3.ɵa)) { return this._ɵa_16; }
    if ((token === import3.UrlSerializer)) { return this._UrlSerializer_17; }
    if ((token === import3.RouterOutletMap)) { return this._RouterOutletMap_18; }
    if ((token === import3.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_19; }
    if ((token === import2.LocationStrategy)) { return this._LocationStrategy_20; }
    if ((token === import2.Location)) { return this._Location_21; }
    if ((token === import0.Compiler)) { return this._Compiler_22; }
    if ((token === import0.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_23; }
    if ((token === import3.ROUTES)) { return this._ROUTES_24; }
    if ((token === import3.Router)) { return this._Router_25; }
    if ((token === import3.RouterModule)) { return this._RouterModule_26; }
    if ((token === import7.BookRoutingModule)) { return this._BookRoutingModule_27; }
    if ((token === import8.UtilitiesModule)) { return this._UtilitiesModule_28; }
    if ((token === import9.BookModule)) { return this._BookModule_29; }
    if ((token === import10.LoadingRoutingModule)) { return this._LoadingRoutingModule_30; }
    if ((token === import11.LoadingModule)) { return this._LoadingModule_31; }
    if ((token === import12.AppRoutingModule)) { return this._AppRoutingModule_32; }
    if ((token === import1.AppModule)) { return this._AppModule_33; }
    if ((token === import0.LOCALE_ID)) { return this._LOCALE_ID_34; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_35; }
    if ((token === import0.IterableDiffers)) { return this._IterableDiffers_36; }
    if ((token === import0.KeyValueDiffers)) { return this._KeyValueDiffers_37; }
    if ((token === import4.DomSanitizer)) { return this._DomSanitizer_38; }
    if ((token === import0.Sanitizer)) { return this._Sanitizer_39; }
    if ((token === import4.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_40; }
    if ((token === import4.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_41; }
    if ((token === import4.EventManager)) { return this._EventManager_42; }
    if ((token === import4.ɵDomSharedStylesHost)) { return this._ɵDomSharedStylesHost_43; }
    if ((token === import4.ɵDomRendererFactory2)) { return this._ɵDomRendererFactory2_44; }
    if ((token === import0.RendererFactory2)) { return this._RendererFactory2_45; }
    if ((token === import4.ɵSharedStylesHost)) { return this._ɵSharedStylesHost_46; }
    if ((token === import0.Testability)) { return this._Testability_47; }
    if ((token === import4.Meta)) { return this._Meta_48; }
    if ((token === import4.Title)) { return this._Title_49; }
    if ((token === import5.ɵi)) { return this._ɵi_50; }
    if ((token === import5.FormBuilder)) { return this._FormBuilder_51; }
    if ((token === import6.BrowserXhr)) { return this._BrowserXhr_52; }
    if ((token === import6.ResponseOptions)) { return this._ResponseOptions_53; }
    if ((token === import6.XSRFStrategy)) { return this._XSRFStrategy_54; }
    if ((token === import6.XHRBackend)) { return this._XHRBackend_55; }
    if ((token === import6.RequestOptions)) { return this._RequestOptions_56; }
    if ((token === import6.Http)) { return this._Http_57; }
    if ((token === import13.BookEditGuard)) { return this._BookEditGuard_58; }
    if ((token === import14.BookBus)) { return this._BookBus_59; }
    if ((token === import15.BookService)) { return this._BookService_60; }
    if ((token === import16.GoogleBooksService)) { return this._GoogleBooksService_61; }
    if ((token === import17.BookResolver)) { return this._BookResolver_62; }
    if ((token === import3.ActivatedRoute)) { return this._ActivatedRoute_63; }
    if ((token === import3.NoPreloading)) { return this._NoPreloading_64; }
    if ((token === import3.PreloadingStrategy)) { return this._PreloadingStrategy_65; }
    if ((token === import3.RouterPreloader)) { return this._RouterPreloader_66; }
    if ((token === import3.PreloadAllModules)) { return this._PreloadAllModules_67; }
    if ((token === import3.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_68; }
    if ((token === import0.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_69; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ɵf_8.ngOnDestroy();
    (this.__ɵDomSharedStylesHost_43 && this._ɵDomSharedStylesHost_43.ngOnDestroy());
    (this.__RouterPreloader_66 && this._RouterPreloader_66.ngOnDestroy());
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory<any>(AppModuleInjector,import1.AppModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovd29ya2JlbmNoL3RyYWluaW5ncy9hbmd1bGFyL25nLXB3YS9zcmMvYXBwL2FwcC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovd29ya2JlbmNoL3RyYWluaW5ncy9hbmd1bGFyL25nLXB3YS9zcmMvYXBwL2FwcC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
