/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../src/app/app.server.module';
import * as import2 from '@angular/http';
import * as import3 from '@angular/common';
import * as import4 from '@angular/router';
import * as import5 from '@angular/platform-browser';
import * as import6 from '@angular/platform-browser/animations';
import * as import7 from '@angular/platform-server';
import * as import8 from '@angular/forms';
import * as import9 from '../../../../src/app/book/book.routing.module';
import * as import10 from '../../../../src/app/utilities/utilities.module';
import * as import11 from '../../../../src/app/book/book.module';
import * as import12 from '../../../../src/app/loading/loading-routing.module';
import * as import13 from '../../../../src/app/loading/loading.module';
import * as import14 from '../../../../src/app/app.routing.module';
import * as import15 from '../../../../src/app/app.module';
import * as import16 from '@angular/animations/browser';
import * as import17 from '../../../../src/app/book/core/guards/book-edit.guard';
import * as import18 from '../../../../src/app/book/core/book.bus';
import * as import19 from '../../../../src/app/book/core/book.service';
import * as import20 from '../../../../src/app/book/core/google-books.service';
import * as import21 from '../../../../src/app/book/core/resolvers/book.resolver';
import * as import22 from './book/book-dashboard/book-dashboard.component.ngfactory';
import * as import23 from './book/book-details/book-details.component.ngfactory';
import * as import24 from './book/book-edit/book-edit.component.ngfactory';
import * as import25 from './loading/app-loading-indicator/app-loading-indicator.component.ngfactory';
import * as import26 from './not-found/not-found.component.ngfactory';
import * as import27 from './app.component.ngfactory';
import * as import28 from '../../../../src/app/book/book-dashboard/book-dashboard.component';
import * as import29 from '../../../../src/app/book/book-details/book-details.component';
import * as import30 from '../../../../src/app/book/book-edit/book-edit.component';
import * as import31 from '../../../../src/app/loading/app-loading-indicator/app-loading-indicator.component';
import * as import32 from '../../../../src/app/not-found/not-found.component';
class AppServerModuleInjector extends import0.ɵNgModuleInjector<import1.AppServerModule> {
  _HttpModule_0:import2.HttpModule;
  _CommonModule_1:import3.CommonModule;
  _ErrorHandler_2:any;
  _NgProbeToken_3:any[];
  _ɵg_4:import4.ɵg;
  _APP_ID_5:any;
  _ɵTRANSITION_ID_6:any;
  _APP_INITIALIZER_7:any[];
  _ApplicationInitStatus_8:import0.ApplicationInitStatus;
  _ɵf_9:import0.ɵf;
  _ApplicationRef_10:any;
  _ApplicationModule_11:import0.ApplicationModule;
  _BrowserModule_12:import5.BrowserModule;
  _NoopAnimationsModule_13:import6.NoopAnimationsModule;
  _ServerModule_14:import7.ServerModule;
  _ɵba_15:import8.ɵba;
  _FormsModule_16:import8.FormsModule;
  _ReactiveFormsModule_17:import8.ReactiveFormsModule;
  _ɵa_18:any;
  _UrlSerializer_19:import4.DefaultUrlSerializer;
  _RouterOutletMap_20:import4.RouterOutletMap;
  _ROUTER_CONFIGURATION_21:any;
  _LocationStrategy_22:any;
  _Location_23:import3.Location;
  _Compiler_24:import0.Compiler;
  _NgModuleFactoryLoader_25:import0.SystemJsNgModuleLoader;
  _ROUTES_26:any[];
  _Router_27:any;
  _RouterModule_28:import4.RouterModule;
  _BookRoutingModule_29:import9.BookRoutingModule;
  _UtilitiesModule_30:import10.UtilitiesModule;
  _BookModule_31:import11.BookModule;
  _LoadingRoutingModule_32:import12.LoadingRoutingModule;
  _LoadingModule_33:import13.LoadingModule;
  _AppRoutingModule_34:import14.AppRoutingModule;
  _AppModule_35:import15.AppModule;
  _AppServerModule_36:import1.AppServerModule;
  __BrowserXhr_37:import7.ɵc;
  __ResponseOptions_38:import2.BaseResponseOptions;
  __XSRFStrategy_39:import7.ɵd;
  __XHRBackend_40:import2.XHRBackend;
  __RequestOptions_41:import2.BaseRequestOptions;
  __Http_42:any;
  __LOCALE_ID_43:any;
  __NgLocalization_44:import3.NgLocaleLocalization;
  __IterableDiffers_45:any;
  __KeyValueDiffers_46:any;
  __DomSanitizer_47:import5.ɵe;
  __Sanitizer_48:any;
  __HAMMER_GESTURE_CONFIG_49:import5.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_50:any[];
  __EventManager_51:import5.EventManager;
  __ɵDomSharedStylesHost_52:import5.ɵDomSharedStylesHost;
  __ɵDomRendererFactory2_53:import5.ɵDomRendererFactory2;
  __ɵb_54:import7.ɵb;
  __ɵSharedStylesHost_55:any;
  __ɵServerRendererFactory2_56:import7.ɵServerRendererFactory2;
  __ɵAnimationEngine_57:import16.ɵNoopAnimationEngine;
  __RendererFactory2_58:any;
  __Testability_59:any;
  __Meta_60:import5.Meta;
  __Title_61:import5.Title;
  __ɵi_62:import8.ɵi;
  __FormBuilder_63:import8.FormBuilder;
  __BookEditGuard_64:import17.BookEditGuard;
  __BookBus_65:import18.BookBus;
  __BookService_66:import19.BookService;
  __GoogleBooksService_67:import20.GoogleBooksService;
  __BookResolver_68:import21.BookResolver;
  __ActivatedRoute_69:any;
  __NoPreloading_70:import4.NoPreloading;
  __PreloadingStrategy_71:any;
  __RouterPreloader_72:import4.RouterPreloader;
  __PreloadAllModules_73:import4.PreloadAllModules;
  __ROUTER_INITIALIZER_74:any;
  __APP_BOOTSTRAP_LISTENER_75:any[];
  constructor(parent:import0.Injector) {
    super(parent,[
      import22.BookDashboardComponentNgFactory,
      import23.BookDetailsComponentNgFactory,
      import24.BookEditComponentNgFactory,
      import25.AppLoadingIndicatorComponentNgFactory,
      import26.NotFoundComponentNgFactory,
      import27.AppComponentNgFactory
    ]
    ,[import27.AppComponentNgFactory]);
  }
  get _BrowserXhr_37():import7.ɵc {
    if ((this.__BrowserXhr_37 == null)) { (this.__BrowserXhr_37 = new import7.ɵc()); }
    return this.__BrowserXhr_37;
  }
  get _ResponseOptions_38():import2.BaseResponseOptions {
    if ((this.__ResponseOptions_38 == null)) { (this.__ResponseOptions_38 = new import2.BaseResponseOptions()); }
    return this.__ResponseOptions_38;
  }
  get _XSRFStrategy_39():import7.ɵd {
    if ((this.__XSRFStrategy_39 == null)) { (this.__XSRFStrategy_39 = new import7.ɵd()); }
    return this.__XSRFStrategy_39;
  }
  get _XHRBackend_40():import2.XHRBackend {
    if ((this.__XHRBackend_40 == null)) { (this.__XHRBackend_40 = new import2.XHRBackend(this._BrowserXhr_37,this._ResponseOptions_38,this._XSRFStrategy_39)); }
    return this.__XHRBackend_40;
  }
  get _RequestOptions_41():import2.BaseRequestOptions {
    if ((this.__RequestOptions_41 == null)) { (this.__RequestOptions_41 = new import2.BaseRequestOptions()); }
    return this.__RequestOptions_41;
  }
  get _Http_42():any {
    if ((this.__Http_42 == null)) { (this.__Http_42 = import7.ɵe(this._XHRBackend_40,this._RequestOptions_41)); }
    return this.__Http_42;
  }
  get _LOCALE_ID_43():any {
    if ((this.__LOCALE_ID_43 == null)) { (this.__LOCALE_ID_43 = import0.ɵn(this.parent.get(import0.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_43;
  }
  get _NgLocalization_44():import3.NgLocaleLocalization {
    if ((this.__NgLocalization_44 == null)) { (this.__NgLocalization_44 = new import3.NgLocaleLocalization(this._LOCALE_ID_43)); }
    return this.__NgLocalization_44;
  }
  get _IterableDiffers_45():any {
    if ((this.__IterableDiffers_45 == null)) { (this.__IterableDiffers_45 = import0.ɵl()); }
    return this.__IterableDiffers_45;
  }
  get _KeyValueDiffers_46():any {
    if ((this.__KeyValueDiffers_46 == null)) { (this.__KeyValueDiffers_46 = import0.ɵm()); }
    return this.__KeyValueDiffers_46;
  }
  get _DomSanitizer_47():import5.ɵe {
    if ((this.__DomSanitizer_47 == null)) { (this.__DomSanitizer_47 = new import5.ɵe(this.parent.get(import5.DOCUMENT))); }
    return this.__DomSanitizer_47;
  }
  get _Sanitizer_48():any {
    if ((this.__Sanitizer_48 == null)) { (this.__Sanitizer_48 = this._DomSanitizer_47); }
    return this.__Sanitizer_48;
  }
  get _HAMMER_GESTURE_CONFIG_49():import5.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_49 == null)) { (this.__HAMMER_GESTURE_CONFIG_49 = new import5.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_49;
  }
  get _EVENT_MANAGER_PLUGINS_50():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_50 == null)) { (this.__EVENT_MANAGER_PLUGINS_50 = [
      new import5.ɵDomEventsPlugin(this.parent.get(import5.DOCUMENT)),
      new import5.ɵKeyEventsPlugin(this.parent.get(import5.DOCUMENT)),
      new import5.ɵHammerGesturesPlugin(this.parent.get(import5.DOCUMENT),this._HAMMER_GESTURE_CONFIG_49)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_50;
  }
  get _EventManager_51():import5.EventManager {
    if ((this.__EventManager_51 == null)) { (this.__EventManager_51 = new import5.EventManager(this._EVENT_MANAGER_PLUGINS_50,this.parent.get(import0.NgZone))); }
    return this.__EventManager_51;
  }
  get _ɵDomSharedStylesHost_52():import5.ɵDomSharedStylesHost {
    if ((this.__ɵDomSharedStylesHost_52 == null)) { (this.__ɵDomSharedStylesHost_52 = new import5.ɵDomSharedStylesHost(this.parent.get(import5.DOCUMENT))); }
    return this.__ɵDomSharedStylesHost_52;
  }
  get _ɵDomRendererFactory2_53():import5.ɵDomRendererFactory2 {
    if ((this.__ɵDomRendererFactory2_53 == null)) { (this.__ɵDomRendererFactory2_53 = new import5.ɵDomRendererFactory2(this._EventManager_51,this._ɵDomSharedStylesHost_52)); }
    return this.__ɵDomRendererFactory2_53;
  }
  get _ɵb_54():import7.ɵb {
    if ((this.__ɵb_54 == null)) { (this.__ɵb_54 = new import7.ɵb(this.parent.get(import5.DOCUMENT),this._ɵTRANSITION_ID_6)); }
    return this.__ɵb_54;
  }
  get _ɵSharedStylesHost_55():any {
    if ((this.__ɵSharedStylesHost_55 == null)) { (this.__ɵSharedStylesHost_55 = this._ɵb_54); }
    return this.__ɵSharedStylesHost_55;
  }
  get _ɵServerRendererFactory2_56():import7.ɵServerRendererFactory2 {
    if ((this.__ɵServerRendererFactory2_56 == null)) { (this.__ɵServerRendererFactory2_56 = new import7.ɵServerRendererFactory2(this.parent.get(import0.NgZone),this.parent.get(import5.DOCUMENT),this._ɵSharedStylesHost_55)); }
    return this.__ɵServerRendererFactory2_56;
  }
  get _ɵAnimationEngine_57():import16.ɵNoopAnimationEngine {
    if ((this.__ɵAnimationEngine_57 == null)) { (this.__ɵAnimationEngine_57 = new import16.ɵNoopAnimationEngine()); }
    return this.__ɵAnimationEngine_57;
  }
  get _RendererFactory2_58():any {
    if ((this.__RendererFactory2_58 == null)) { (this.__RendererFactory2_58 = import7.ɵa(this._ɵServerRendererFactory2_56,this._ɵAnimationEngine_57,this.parent.get(import0.NgZone))); }
    return this.__RendererFactory2_58;
  }
  get _Testability_59():any {
    if ((this.__Testability_59 == null)) { (this.__Testability_59 = (null as any)); }
    return this.__Testability_59;
  }
  get _Meta_60():import5.Meta {
    if ((this.__Meta_60 == null)) { (this.__Meta_60 = new import5.Meta(this.parent.get(import5.DOCUMENT))); }
    return this.__Meta_60;
  }
  get _Title_61():import5.Title {
    if ((this.__Title_61 == null)) { (this.__Title_61 = new import5.Title(this.parent.get(import5.DOCUMENT))); }
    return this.__Title_61;
  }
  get _ɵi_62():import8.ɵi {
    if ((this.__ɵi_62 == null)) { (this.__ɵi_62 = new import8.ɵi()); }
    return this.__ɵi_62;
  }
  get _FormBuilder_63():import8.FormBuilder {
    if ((this.__FormBuilder_63 == null)) { (this.__FormBuilder_63 = new import8.FormBuilder()); }
    return this.__FormBuilder_63;
  }
  get _BookEditGuard_64():import17.BookEditGuard {
    if ((this.__BookEditGuard_64 == null)) { (this.__BookEditGuard_64 = new import17.BookEditGuard()); }
    return this.__BookEditGuard_64;
  }
  get _BookBus_65():import18.BookBus {
    if ((this.__BookBus_65 == null)) { (this.__BookBus_65 = new import18.BookBus()); }
    return this.__BookBus_65;
  }
  get _BookService_66():import19.BookService {
    if ((this.__BookService_66 == null)) { (this.__BookService_66 = new import19.BookService()); }
    return this.__BookService_66;
  }
  get _GoogleBooksService_67():import20.GoogleBooksService {
    if ((this.__GoogleBooksService_67 == null)) { (this.__GoogleBooksService_67 = new import20.GoogleBooksService(this._Http_42)); }
    return this.__GoogleBooksService_67;
  }
  get _BookResolver_68():import21.BookResolver {
    if ((this.__BookResolver_68 == null)) { (this.__BookResolver_68 = new import21.BookResolver(this._BookService_66)); }
    return this.__BookResolver_68;
  }
  get _ActivatedRoute_69():any {
    if ((this.__ActivatedRoute_69 == null)) { (this.__ActivatedRoute_69 = import4.ɵf(this._Router_27)); }
    return this.__ActivatedRoute_69;
  }
  get _NoPreloading_70():import4.NoPreloading {
    if ((this.__NoPreloading_70 == null)) { (this.__NoPreloading_70 = new import4.NoPreloading()); }
    return this.__NoPreloading_70;
  }
  get _PreloadingStrategy_71():any {
    if ((this.__PreloadingStrategy_71 == null)) { (this.__PreloadingStrategy_71 = this._NoPreloading_70); }
    return this.__PreloadingStrategy_71;
  }
  get _RouterPreloader_72():import4.RouterPreloader {
    if ((this.__RouterPreloader_72 == null)) { (this.__RouterPreloader_72 = new import4.RouterPreloader(this._Router_27,this._NgModuleFactoryLoader_25,this._Compiler_24,this,this._PreloadingStrategy_71)); }
    return this.__RouterPreloader_72;
  }
  get _PreloadAllModules_73():import4.PreloadAllModules {
    if ((this.__PreloadAllModules_73 == null)) { (this.__PreloadAllModules_73 = new import4.PreloadAllModules()); }
    return this.__PreloadAllModules_73;
  }
  get _ROUTER_INITIALIZER_74():any {
    if ((this.__ROUTER_INITIALIZER_74 == null)) { (this.__ROUTER_INITIALIZER_74 = import4.ɵi(this._ɵg_4)); }
    return this.__ROUTER_INITIALIZER_74;
  }
  get _APP_BOOTSTRAP_LISTENER_75():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_75 == null)) { (this.__APP_BOOTSTRAP_LISTENER_75 = [this._ROUTER_INITIALIZER_74]); }
    return this.__APP_BOOTSTRAP_LISTENER_75;
  }
  createInternal():import1.AppServerModule {
    this._HttpModule_0 = new import2.HttpModule();
    this._CommonModule_1 = new import3.CommonModule();
    this._ErrorHandler_2 = import5.ɵa();
    this._NgProbeToken_3 = [import4.ɵb()];
    this._ɵg_4 = new import4.ɵg(this);
    this._APP_ID_5 = 'buecher';
    this._ɵTRANSITION_ID_6 = this._APP_ID_5;
    this._APP_INITIALIZER_7 = [
      import0.ɵo,
      import5.ɵc(this.parent.get(import5.NgProbeToken,(null as any)),this._NgProbeToken_3),
      import4.ɵh(this._ɵg_4),
      import5.ɵf(this._ɵTRANSITION_ID_6,this.parent.get(import5.DOCUMENT),this)
    ]
    ;
    this._ApplicationInitStatus_8 = new import0.ApplicationInitStatus(this._APP_INITIALIZER_7);
    this._ɵf_9 = new import0.ɵf(this.parent.get(import0.NgZone),this.parent.get(import0.ɵConsole),this,this._ErrorHandler_2,this.componentFactoryResolver,this._ApplicationInitStatus_8);
    this._ApplicationRef_10 = this._ɵf_9;
    this._ApplicationModule_11 = new import0.ApplicationModule(this._ApplicationRef_10);
    this._BrowserModule_12 = new import5.BrowserModule(this.parent.get(import5.BrowserModule,(null as any)));
    this._NoopAnimationsModule_13 = new import6.NoopAnimationsModule();
    this._ServerModule_14 = new import7.ServerModule();
    this._ɵba_15 = new import8.ɵba();
    this._FormsModule_16 = new import8.FormsModule();
    this._ReactiveFormsModule_17 = new import8.ReactiveFormsModule();
    this._ɵa_18 = import4.ɵd(this.parent.get(import4.Router,(null as any)));
    this._UrlSerializer_19 = new import4.DefaultUrlSerializer();
    this._RouterOutletMap_20 = new import4.RouterOutletMap();
    this._ROUTER_CONFIGURATION_21 = {};
    this._LocationStrategy_22 = import4.ɵc(this.parent.get(import3.PlatformLocation),this.parent.get(import3.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_21);
    this._Location_23 = new import3.Location(this._LocationStrategy_22);
    this._Compiler_24 = new import0.Compiler();
    this._NgModuleFactoryLoader_25 = new import0.SystemJsNgModuleLoader(this._Compiler_24,this.parent.get(import0.SystemJsNgModuleLoaderConfig,(null as any)));
    this._ROUTES_26 = [
      [
        {
          path: '',
          component: import28.BookDashboardComponent,
          pathMatch: 'full'
        }
        ,
        {
          path: 'book/:isbn',
          component: import29.BookDetailsComponent,
          resolve: {book: import21.BookResolver}
        }
        ,
        {
          path: 'book/:isbn/edit',
          component: import30.BookEditComponent,
          resolve: {book: import21.BookResolver},
          canActivate: [import17.BookEditGuard]
        }

      ]
      ,
        [{
          path: 'loading',
          component: import31.AppLoadingIndicatorComponent
        }
      ],
        [{
          path: '**',
          component: import32.NotFoundComponent
        }
      ]
    ]
    ;
    this._Router_27 = import4.ɵe(this._ApplicationRef_10,this._UrlSerializer_19,this._RouterOutletMap_20,this._Location_23,this,this._NgModuleFactoryLoader_25,this._Compiler_24,this._ROUTES_26,this._ROUTER_CONFIGURATION_21,this.parent.get(import4.UrlHandlingStrategy,(null as any)),this.parent.get(import4.RouteReuseStrategy,(null as any)));
    this._RouterModule_28 = new import4.RouterModule(this._ɵa_18,this._Router_27);
    this._BookRoutingModule_29 = new import9.BookRoutingModule();
    this._UtilitiesModule_30 = new import10.UtilitiesModule();
    this._BookModule_31 = new import11.BookModule();
    this._LoadingRoutingModule_32 = new import12.LoadingRoutingModule();
    this._LoadingModule_33 = new import13.LoadingModule();
    this._AppRoutingModule_34 = new import14.AppRoutingModule();
    this._AppModule_35 = new import15.AppModule();
    this._AppServerModule_36 = new import1.AppServerModule();
    return this._AppServerModule_36;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.HttpModule)) { return this._HttpModule_0; }
    if ((token === import3.CommonModule)) { return this._CommonModule_1; }
    if ((token === import0.ErrorHandler)) { return this._ErrorHandler_2; }
    if ((token === import0.NgProbeToken)) { return this._NgProbeToken_3; }
    if ((token === import4.ɵg)) { return this._ɵg_4; }
    if ((token === import0.APP_ID)) { return this._APP_ID_5; }
    if ((token === import5.ɵTRANSITION_ID)) { return this._ɵTRANSITION_ID_6; }
    if ((token === import0.APP_INITIALIZER)) { return this._APP_INITIALIZER_7; }
    if ((token === import0.ApplicationInitStatus)) { return this._ApplicationInitStatus_8; }
    if ((token === import0.ɵf)) { return this._ɵf_9; }
    if ((token === import0.ApplicationRef)) { return this._ApplicationRef_10; }
    if ((token === import0.ApplicationModule)) { return this._ApplicationModule_11; }
    if ((token === import5.BrowserModule)) { return this._BrowserModule_12; }
    if ((token === import6.NoopAnimationsModule)) { return this._NoopAnimationsModule_13; }
    if ((token === import7.ServerModule)) { return this._ServerModule_14; }
    if ((token === import8.ɵba)) { return this._ɵba_15; }
    if ((token === import8.FormsModule)) { return this._FormsModule_16; }
    if ((token === import8.ReactiveFormsModule)) { return this._ReactiveFormsModule_17; }
    if ((token === import4.ɵa)) { return this._ɵa_18; }
    if ((token === import4.UrlSerializer)) { return this._UrlSerializer_19; }
    if ((token === import4.RouterOutletMap)) { return this._RouterOutletMap_20; }
    if ((token === import4.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_21; }
    if ((token === import3.LocationStrategy)) { return this._LocationStrategy_22; }
    if ((token === import3.Location)) { return this._Location_23; }
    if ((token === import0.Compiler)) { return this._Compiler_24; }
    if ((token === import0.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_25; }
    if ((token === import4.ROUTES)) { return this._ROUTES_26; }
    if ((token === import4.Router)) { return this._Router_27; }
    if ((token === import4.RouterModule)) { return this._RouterModule_28; }
    if ((token === import9.BookRoutingModule)) { return this._BookRoutingModule_29; }
    if ((token === import10.UtilitiesModule)) { return this._UtilitiesModule_30; }
    if ((token === import11.BookModule)) { return this._BookModule_31; }
    if ((token === import12.LoadingRoutingModule)) { return this._LoadingRoutingModule_32; }
    if ((token === import13.LoadingModule)) { return this._LoadingModule_33; }
    if ((token === import14.AppRoutingModule)) { return this._AppRoutingModule_34; }
    if ((token === import15.AppModule)) { return this._AppModule_35; }
    if ((token === import1.AppServerModule)) { return this._AppServerModule_36; }
    if ((token === import2.BrowserXhr)) { return this._BrowserXhr_37; }
    if ((token === import2.ResponseOptions)) { return this._ResponseOptions_38; }
    if ((token === import2.XSRFStrategy)) { return this._XSRFStrategy_39; }
    if ((token === import2.XHRBackend)) { return this._XHRBackend_40; }
    if ((token === import2.RequestOptions)) { return this._RequestOptions_41; }
    if ((token === import2.Http)) { return this._Http_42; }
    if ((token === import0.LOCALE_ID)) { return this._LOCALE_ID_43; }
    if ((token === import3.NgLocalization)) { return this._NgLocalization_44; }
    if ((token === import0.IterableDiffers)) { return this._IterableDiffers_45; }
    if ((token === import0.KeyValueDiffers)) { return this._KeyValueDiffers_46; }
    if ((token === import5.DomSanitizer)) { return this._DomSanitizer_47; }
    if ((token === import0.Sanitizer)) { return this._Sanitizer_48; }
    if ((token === import5.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_49; }
    if ((token === import5.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_50; }
    if ((token === import5.EventManager)) { return this._EventManager_51; }
    if ((token === import5.ɵDomSharedStylesHost)) { return this._ɵDomSharedStylesHost_52; }
    if ((token === import5.ɵDomRendererFactory2)) { return this._ɵDomRendererFactory2_53; }
    if ((token === import7.ɵb)) { return this._ɵb_54; }
    if ((token === import5.ɵSharedStylesHost)) { return this._ɵSharedStylesHost_55; }
    if ((token === import7.ɵServerRendererFactory2)) { return this._ɵServerRendererFactory2_56; }
    if ((token === import16.ɵAnimationEngine)) { return this._ɵAnimationEngine_57; }
    if ((token === import0.RendererFactory2)) { return this._RendererFactory2_58; }
    if ((token === import0.Testability)) { return this._Testability_59; }
    if ((token === import5.Meta)) { return this._Meta_60; }
    if ((token === import5.Title)) { return this._Title_61; }
    if ((token === import8.ɵi)) { return this._ɵi_62; }
    if ((token === import8.FormBuilder)) { return this._FormBuilder_63; }
    if ((token === import17.BookEditGuard)) { return this._BookEditGuard_64; }
    if ((token === import18.BookBus)) { return this._BookBus_65; }
    if ((token === import19.BookService)) { return this._BookService_66; }
    if ((token === import20.GoogleBooksService)) { return this._GoogleBooksService_67; }
    if ((token === import21.BookResolver)) { return this._BookResolver_68; }
    if ((token === import4.ActivatedRoute)) { return this._ActivatedRoute_69; }
    if ((token === import4.NoPreloading)) { return this._NoPreloading_70; }
    if ((token === import4.PreloadingStrategy)) { return this._PreloadingStrategy_71; }
    if ((token === import4.RouterPreloader)) { return this._RouterPreloader_72; }
    if ((token === import4.PreloadAllModules)) { return this._PreloadAllModules_73; }
    if ((token === import4.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_74; }
    if ((token === import0.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_75; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ɵf_9.ngOnDestroy();
    (this.__ɵDomSharedStylesHost_52 && this._ɵDomSharedStylesHost_52.ngOnDestroy());
    (this.__RouterPreloader_72 && this._RouterPreloader_72.ngOnDestroy());
  }
}
export const AppServerModuleNgFactory:import0.NgModuleFactory<import1.AppServerModule> = new import0.NgModuleFactory<any>(AppServerModuleInjector,import1.AppServerModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovd29ya2JlbmNoL3RyYWluaW5ncy9hbmd1bGFyL25nLXB3YS9zcmMvYXBwL2FwcC5zZXJ2ZXIubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L3dvcmtiZW5jaC90cmFpbmluZ3MvYW5ndWxhci9uZy1wd2Evc3JjL2FwcC9hcHAuc2VydmVyLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
