/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['\\-shadowcsshost-no-combinator\r\n  margin-top: 32px\r\n  display: flex\r\n  flex-direction: row\r\n  flex-flow: row wrap\r\n  justify-content: space-between'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovd29ya2JlbmNoL3RyYWluaW5ncy9hbmd1bGFyL25nLXB3YS9zcmMvYXBwL2Jvb2svYm9vay1ncmlkL2Jvb2stZ3JpZC5jb21wb25lbnQuc2Fzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi93b3JrYmVuY2gvdHJhaW5pbmdzL2FuZ3VsYXIvbmctcHdhL3NyYy9hcHAvYm9vay9ib29rLWdyaWQvYm9vay1ncmlkLmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
