/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from './book-grid.component.sass.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '../book-grid-element/book-grid-element.component.ngfactory';
import * as import3 from '../../../../../../src/app/book/book-grid-element/book-grid-element.component';
import * as import4 from '../../../../../../src/app/book/core/book.bus';
import * as import5 from '@angular/common';
import * as import6 from '../../../../../../src/app/book/book-grid/book-grid.component';
const styles_BookGridComponent:any[] = [import0.styles];
export const RenderType_BookGridComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_BookGridComponent,
  data: {}
}
);
function View_BookGridComponent_1(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),2,'tr-book-card',([] as any[]),(null as any),(null as any),(null as any),import2.View_BookGridElementComponent_0,import2.RenderType_BookGridElementComponent)),
      import1.ɵdid(49152,(null as any),0,import3.BookGridElementComponent,[import4.BookBus],{book: [
        0,
        'book'
      ]
    },(null as any)),
    (l()(),import1.ɵted((null as any),['\n']))
  ]
  ,(ck,v) => {
    const currVal_0:any = v.context.$implicit;
    ck(v,1,0,currVal_0);
  },(null as any));
}
export function View_BookGridComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵand(16777216,(null as any),(null as any),1,(null as any),View_BookGridComponent_1)),
    import1.ɵdid(802816,(null as any),0,import5.NgForOf,[
      import1.ViewContainerRef,
      import1.TemplateRef,
      import1.IterableDiffers
    ]
      ,{ngForOf: [
        0,
        'ngForOf'
      ]
    },(null as any)),
    (l()(),import1.ɵted((null as any),['\n']))
  ]
  ,(ck,v) => {
    var co:import6.BookGridComponent = v.component;
    const currVal_0:any = co.books;
    ck(v,1,0,currVal_0);
  },(null as any));
}
function View_BookGridComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'tr-book-grid',([] as any[]),(null as any),(null as any),(null as any),View_BookGridComponent_0,RenderType_BookGridComponent)),
    import1.ɵdid(114688,(null as any),0,import6.BookGridComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const BookGridComponentNgFactory:import1.ComponentFactory<import6.BookGridComponent> = import1.ɵccf('tr-book-grid',import6.BookGridComponent,View_BookGridComponent_Host_0,{books: 'books'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovd29ya2JlbmNoL3RyYWluaW5ncy9hbmd1bGFyL25nLXB3YS9zcmMvYXBwL2Jvb2svYm9vay1ncmlkL2Jvb2stZ3JpZC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovd29ya2JlbmNoL3RyYWluaW5ncy9hbmd1bGFyL25nLXB3YS9zcmMvYXBwL2Jvb2svYm9vay1ncmlkL2Jvb2stZ3JpZC5jb21wb25lbnQudHMiLCJuZzovLy9DOi93b3JrYmVuY2gvdHJhaW5pbmdzL2FuZ3VsYXIvbmctcHdhL3NyYy9hcHAvYm9vay9ib29rLWdyaWQvYm9vay1ncmlkLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovd29ya2JlbmNoL3RyYWluaW5ncy9hbmd1bGFyL25nLXB3YS9zcmMvYXBwL2Jvb2svYm9vay1ncmlkL2Jvb2stZ3JpZC5jb21wb25lbnQudHMuQm9va0dyaWRDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8dHItYm9vay1jYXJkXG4gIFtib29rXT1cImJvb2tcIlxuICAqbmdGb3I9XCJsZXQgYm9vayBvZiBib29rc1wiPlxuPC90ci1ib29rLWNhcmQ+XG4iLCI8dHItYm9vay1ncmlkPjwvdHItYm9vay1ncmlkPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztJQ0FBO2tCQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFFNkI7OztJQUQzQjtJQURGLFNBQ0UsU0FERjs7Ozs7SUFBQTtnQkFBQTs7OztJQUFBO09BQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUdlOzs7O0lBRGI7SUFGRixTQUVFLFNBRkY7Ozs7O0lDQUE7Z0JBQUE7OztJQUFBOzs7In0=
