/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.tooltip.tooltip-validation\r\n  width: 100%'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovd29ya2JlbmNoL3RyYWluaW5ncy9hbmd1bGFyL25nLXB3YS9zcmMvYXBwL2Jvb2svYm9vay1hZGQtZm9ybS9ib29rLWFkZC1mb3JtLmNvbXBvbmVudC5zYXNzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L3dvcmtiZW5jaC90cmFpbmluZ3MvYW5ndWxhci9uZy1wd2Evc3JjL2FwcC9ib29rL2Jvb2stYWRkLWZvcm0vYm9vay1hZGQtZm9ybS5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
