/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['\\-shadowcsshost-no-combinator   display[_ngcontent-%COMP%]:   flex[_ngcontent-%COMP%]   flex-direction[_ngcontent-%COMP%]:   column[_ngcontent-%COMP%]   padding-bottom[_ngcontent-%COMP%]:   16px[_ngcontent-%COMP%]   &[_ngcontent-%COMP%]:hover   box-shadow[_ngcontent-%COMP%]:   5px[_ngcontent-%COMP%]   5px[_ngcontent-%COMP%]   10px[_ngcontent-%COMP%]   0px[_ngcontent-%COMP%]   rgba(212[_ngcontent-%COMP%], 212[_ngcontent-%COMP%], 212[_ngcontent-%COMP%], 1)[_ngcontent-%COMP%];\r\n\r\n  a\r\n    color: #565656\r\n    text-decoration: none\r\n\r\n    .thumbnail\r\n      text-align: center\r\n\r\n  .actions\r\n    margin-top: 8px\r\n    display: flex\r\n    justify-content: center'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovd29ya2JlbmNoL3RyYWluaW5ncy9hbmd1bGFyL25nLXB3YS9zcmMvYXBwL2Jvb2svYm9vay1ncmlkLWVsZW1lbnQvYm9vay1ncmlkLWVsZW1lbnQuY29tcG9uZW50LnNhc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovd29ya2JlbmNoL3RyYWluaW5ncy9hbmd1bGFyL25nLXB3YS9zcmMvYXBwL2Jvb2svYm9vay1ncmlkLWVsZW1lbnQvYm9vay1ncmlkLWVsZW1lbnQuY29tcG9uZW50LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
