/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from './book-list.component.sass.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '../book-list-element/book-list-element.component.ngfactory';
import * as import3 from '../../../../../../src/app/book/book-list-element/book-list-element.component';
import * as import4 from '../../../../../../src/app/book/core/book.bus';
import * as import5 from '@angular/common';
import * as import6 from '../../../../../../src/app/book/book-list/book-list.component';
const styles_BookListComponent:any[] = [import0.styles];
export const RenderType_BookListComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_BookListComponent,
  data: {}
}
);
function View_BookListComponent_1(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'tr-book-list-element',([] as any[]),(null as any),(null as any),(null as any),import2.View_ListElementComponent_0,import2.RenderType_ListElementComponent)),
      import1.ɵdid(49152,(null as any),0,import3.ListElementComponent,[import4.BookBus],{book: [
        0,
        'book'
      ]
    },(null as any))
  ]
  ,(ck,v) => {
    const currVal_0:any = v.context.$implicit;
    ck(v,1,0,currVal_0);
  },(null as any));
}
export function View_BookListComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵand(16777216,(null as any),(null as any),1,(null as any),View_BookListComponent_1)),
    import1.ɵdid(802816,(null as any),0,import5.NgForOf,[
      import1.ViewContainerRef,
      import1.TemplateRef,
      import1.IterableDiffers
    ]
      ,{ngForOf: [
        0,
        'ngForOf'
      ]
    },(null as any)),
    (l()(),import1.ɵted((null as any),['\n']))
  ]
  ,(ck,v) => {
    var co:import6.BookListComponent = v.component;
    const currVal_0:any = co.books;
    ck(v,1,0,currVal_0);
  },(null as any));
}
function View_BookListComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'tr-book-list',([] as any[]),(null as any),(null as any),(null as any),View_BookListComponent_0,RenderType_BookListComponent)),
    import1.ɵdid(114688,(null as any),0,import6.BookListComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const BookListComponentNgFactory:import1.ComponentFactory<import6.BookListComponent> = import1.ɵccf('tr-book-list',import6.BookListComponent,View_BookListComponent_Host_0,{books: 'books'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovd29ya2JlbmNoL3RyYWluaW5ncy9hbmd1bGFyL25nLXB3YS9zcmMvYXBwL2Jvb2svYm9vay1saXN0L2Jvb2stbGlzdC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovd29ya2JlbmNoL3RyYWluaW5ncy9hbmd1bGFyL25nLXB3YS9zcmMvYXBwL2Jvb2svYm9vay1saXN0L2Jvb2stbGlzdC5jb21wb25lbnQudHMiLCJuZzovLy9DOi93b3JrYmVuY2gvdHJhaW5pbmdzL2FuZ3VsYXIvbmctcHdhL3NyYy9hcHAvYm9vay9ib29rLWxpc3QvYm9vay1saXN0LmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovd29ya2JlbmNoL3RyYWluaW5ncy9hbmd1bGFyL25nLXB3YS9zcmMvYXBwL2Jvb2svYm9vay1saXN0L2Jvb2stbGlzdC5jb21wb25lbnQudHMuQm9va0xpc3RDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8dHItYm9vay1saXN0LWVsZW1lbnQgW2Jvb2tdPVwiYm9va1wiICpuZ0Zvcj1cImxldCBib29rIG9mIGJvb2tzXCI+PC90ci1ib29rLWxpc3QtZWxlbWVudD5cbiIsIjx0ci1ib29rLWxpc3Q+PC90ci1ib29rLWxpc3Q+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDQUE7a0JBQUE7UUFBQTtRQUFBO01BQUE7SUFBQTs7O0lBQXNCO0lBQXRCLFNBQXNCLFNBQXRCOzs7OztJQUFBO2dCQUFBOzs7O0lBQUE7T0FBQTtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQXNGOzs7O0lBQWxEO0lBQXBDLFNBQW9DLFNBQXBDOzs7OztJQ0FBO2dCQUFBOzs7SUFBQTs7OyJ9
