/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from './app-loading-indicator.component.sass.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '../../../../../../src/app/loading/app-loading-indicator/app-loading-indicator.component';
const styles_AppLoadingIndicatorComponent:any[] = [import0.styles];
export const RenderType_AppLoadingIndicatorComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_AppLoadingIndicatorComponent,
  data: {}
}
);
export function View_AppLoadingIndicatorComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'h3',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['App gets prepared for you...'])),
    (l()(),import1.ɵted((null as any),['\n']))
  ]
  ,(null as any),(null as any));
}
function View_AppLoadingIndicatorComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'tr-app-loading-indicator',([] as any[]),(null as any),(null as any),(null as any),View_AppLoadingIndicatorComponent_0,RenderType_AppLoadingIndicatorComponent)),
    import1.ɵdid(114688,(null as any),0,import2.AppLoadingIndicatorComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const AppLoadingIndicatorComponentNgFactory:import1.ComponentFactory<import2.AppLoadingIndicatorComponent> = import1.ɵccf('tr-app-loading-indicator',import2.AppLoadingIndicatorComponent,View_AppLoadingIndicatorComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovd29ya2JlbmNoL3RyYWluaW5ncy9hbmd1bGFyL25nLXB3YS9zcmMvYXBwL2xvYWRpbmcvYXBwLWxvYWRpbmctaW5kaWNhdG9yL2FwcC1sb2FkaW5nLWluZGljYXRvci5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovd29ya2JlbmNoL3RyYWluaW5ncy9hbmd1bGFyL25nLXB3YS9zcmMvYXBwL2xvYWRpbmcvYXBwLWxvYWRpbmctaW5kaWNhdG9yL2FwcC1sb2FkaW5nLWluZGljYXRvci5jb21wb25lbnQudHMiLCJuZzovLy9DOi93b3JrYmVuY2gvdHJhaW5pbmdzL2FuZ3VsYXIvbmctcHdhL3NyYy9hcHAvbG9hZGluZy9hcHAtbG9hZGluZy1pbmRpY2F0b3IvYXBwLWxvYWRpbmctaW5kaWNhdG9yLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovd29ya2JlbmNoL3RyYWluaW5ncy9hbmd1bGFyL25nLXB3YS9zcmMvYXBwL2xvYWRpbmcvYXBwLWxvYWRpbmctaW5kaWNhdG9yL2FwcC1sb2FkaW5nLWluZGljYXRvci5jb21wb25lbnQudHMuQXBwTG9hZGluZ0luZGljYXRvckNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxoMz5BcHAgZ2V0cyBwcmVwYXJlZCBmb3IgeW91Li4uPC9oMz5cbiIsIjx0ci1hcHAtbG9hZGluZy1pbmRpY2F0b3I+PC90ci1hcHAtbG9hZGluZy1pbmRpY2F0b3I+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtJQUFJO0lBQWlDOzs7Ozs7SUNBckM7Z0JBQUE7OztJQUFBOzs7In0=
